Repository sonofagl1tch/AWSDetonationLab, pull requests merged in 2019-04, with the labels that each got.

#80 added nikto webscanner
  awsDetonationLab.template
Labels: enhancement

#82 added packages to fix rfiurl and ssl scanning in nikto
  awsDetonationLab.template
Labels: bug

#83 Update wazuh inspector configuration using service option
  CHANGELOG.md
  additionalInstallationScripts/installWazuh.sh
  awsDetonationLab.template
Labels: enhancement, wazuh
